"あ":
  "する":
    "hiragana": "し"
    "kanji": "為"
  "くる":
    "hiragana": "こ"
    "kanji": "来"
"い":
  "する":
    "hiragana": "し"
    "kanji": "為"
  "くる":
    "hiragana": "き"
    "kanji": "来"
"う":
  "する":
    "hiragana": "する"
    "kanji": "為る"
  "くる":
    "hiragana": "くる"
    "kanji": "来る"
"え":
  "する":
    "hiragana": "すれ"
    "kanji": "為れ"
  "くる":
    "hiragana": "くれ"
    "kanji": "来れ"
"お":
  "する":
    "hiragana": "しよう"
    "kanji": "為よう"
  "くる":
    "hiragana": "こよう"
    "kanji": "来よう"
"て":
  "する":
    "hiragana": "して"
    "kanji": "為て"
  "くる":
    "hiragana": "きて"
    "kanji": "来て"
"た":
  "する":
    "hiragana": "した"
    "kanji": "為た"
  "くる":
    "hiragana": "きた"
    "kanji": "来た"
