"あ":
  "す": "さ"
  "く": "か"
  "ぐ": "が"
  "ぶ": "ば"
  "む": "ま"
  "ぬ": "な"
  "る": "ら"
  "つ": "た"
  "う": "わ"
"い":
  "す": "し"
  "く": "き"
  "ぐ": "ぎ"
  "ぶ": "び"
  "む": "み"
  "ぬ": "に"
  "る": "り"
  "つ": "ち"
  "う": "い"
"う":
  "す": "す"
  "く": "く"
  "ぐ": "ぐ"
  "ぶ": "ぶ"
  "む": "む"
  "ぬ": "ぬ"
  "る": "る"
  "つ": "つ"
  "う": "う"
"え":
  "す": "せ"
  "く": "け"
  "ぐ": "げ"
  "ぶ": "べ"
  "む": "め"
  "ぬ": "ね"
  "る": "れ"
  "つ": "て"
  "う": "え"
"お":
  "す": "そう"
  "く": "こう"
  "ぐ": "ごう"
  "ぶ": "ぼう"
  "む": "もう"
  "ぬ": "のう"
  "る": "ろう"
  "つ": "とう"
  "う": "おう"
"て":
  "す": "して"
  "く": "いて"
  "ぐ": "いで"
  "ぶ": "んで"
  "む": "んで"
  "ぬ": "んで"
  "る": "って"
  "つ": "って"
  "う": "って"
"た":
  "す": "した"
  "く": "いた"
  "ぐ": "いだ"
  "ぶ": "んだ"
  "む": "んだ"
  "ぬ": "んだ"
  "る": "った"
  "つ": "った"
  "う": "った"
